[project]
name = "project2-moskvina-natalia-dpo"
version = "0.1.0"
description = ""
authors = [
    {name = "nmos94",email = "natalya.moskvina74@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "src" },
]

[tool.poetry.scripts]
project = "src.primitive_db.main:main"